publisher/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, validators


class LoginForm(FlaskForm):
    """
    Represents a login form using Flask-WTF.

    Attributes:
        email (StringField): Field for entering the email.
        password (PasswordField): Field for entering the password.
        remember_me (BooleanField): Checkbox for remembering the user.
        submit (SubmitField): Button to submit the form.
    """

    email = StringField('Email', [validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired(), validators.Length(min=4, max=12)])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Submit')

publisher/forms/publish_form.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, SelectField, validators

from services.utils import read_topics


class PublishForm(FlaskForm):
    """
    Represents a form for publishing posts using Flask-WTF.

    Attributes:
        choices (list): List of topic choices for the SelectField.
        post (TextAreaField): Field for entering the post content.
        topic (SelectField): Dropdown for selecting the topic.
        submit (SubmitField): Button to submit the form.
    """

    # Load topic choices from a function
    choices = read_topics()['Topics']

    # Field for entering the post content
    post = TextAreaField('Post', validators=[validators.DataRequired()])

    # Dropdown for selecting the topic
    topic = SelectField('Topic', choices=choices, validators=[validators.DataRequired()])

    # Button to submit the form
    submit = SubmitField('Submit')

publisher/routes/dashboard_route.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required

from models.TopicSubscriptionModel import TopicSubscription
from services import utils
from log.log import logger

dashboard_bp = Blueprint('dashboard_bp', __name__)

topics = utils.read_topics()


@dashboard_bp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard_home():
    """
    Dashboard home route.

    Returns:
        Response: Rendered dashboard template.
    """
    logger.info("Dashboard home route accessed.")

    try:
        data = utils.get_user_data(current_user.id)
        return render_template('dashboard.html', data=data)
    except Exception as e:
        logger.error("Error occurred in dashboard_home: %s", e)
        return "An error occurred."


@dashboard_bp.route('/subscribe_topics', methods=['GET', 'POST'])
@login_required
def subscribe_topics():
    """
    Subscribe to topics route.

    Returns:
        Response: Redirection to the dashboard home page.
    """
    logger.info("Subscribe topics route accessed.")

    try:
        data = request.form.getlist('subscribe_topics[]')
        for topic in data:
            current_user.subscribe_to_topic(topic_name=topic)
            TopicSubscription.add_topic(user=current_user, topic=topic)
        return redirect(url_for('dashboard_bp.dashboard_home'))
    except Exception as e:
        logger.error("Error occurred in subscribe_topics: %s", e)
        return "An error occurred."


@dashboard_bp.route('/unsubscribe_topics', methods=['GET', 'POST'])
@login_required
def unsubscribe_topics():
    """
    Unsubscribe from topics route.

    Returns:
        Response: Redirection to the dashboard home page.
    """
    logger.info("Unsubscribe topics route accessed.")

    try:
        data = request.form.getlist('subscribed_topics[]')
        for topic in data:
            current_user.unsubscribe_from_topic(topic_name=topic)
        return redirect(url_for('dashboard_bp.dashboard_home'))
    except Exception as e:
        logger.error("Error occurred in unsubscribe_topics: %s", e)
        return "An error occurred."

publisher/routes/login_route.py
from flask import render_template, flash, request, redirect, url_for
from flask import Blueprint
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required
from forms.login_form import LoginForm
from models.UserModel import User
from extention import login_manager
from log.log import logger

login_bp = Blueprint('login_bp', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@login_bp.route('/', methods=['GET', 'POST'])
def login():
    """
    Login route.

    GET: Display the login form.
    POST: Process the submitted form data for user login.

    Returns:
        Response: Either the login form or a redirection.
    """
    logger.info("Login route accessed.")

    form = LoginForm()

    try:
        if request.method == 'POST':
            if form.validate_on_submit():
                email = form.email.data
                password = form.password.data
                remember = form.remember_me.data
                user = User.query.filter_by(email=email).first()
                if not user:
                    flash("User does not exist. Please register.")
                else:
                    if check_password_hash(user.hashed_password, password):
                        login_user(user, remember=remember)
                        logger.info("User logged in successfully.")
                        return redirect(url_for('dashboard_bp.dashboard_home'))
                    else:
                        flash("Email or password incorrect.")
        return render_template('login.html', form=form)
    except Exception as e:
        logger.error("Error occurred during user login: %s", e)
        flash("An error occurred during login.")
        return render_template('login.html', form=form)


@login_bp.route('/logout', methods=['GET'])
@login_required
def logout():
    """
    Logout route.

    Returns:
        Response: Redirection to the login page.
    """
    logger.info("Logout route accessed.")

    logout_user()
    flash("User logged out!")
    return redirect(url_for('login_bp.login', _method='GET'))

publisher/routes/publisher_route.py
from flask import url_for, redirect, render_template, flash
from flask import Blueprint
from flask_login import current_user, login_required

from services import utils, publish_utils
from forms.publish_form import PublishForm
from log.log import logger

publish_bp = Blueprint('publish_bp', __name__)


@publish_bp.route('/', methods=['GET'])
@login_required
def publisher_home():
    """
    Display the publisher's home page.

    Returns:
        Response: The rendered template for the publisher's home page.
    """
    logger.info("Publisher home route accessed.")

    data = utils.get_user_data(current_user.id)
    form = PublishForm()
    form.topic.choices = data['topics_subscribed']
    if not form.topic.choices:
        flash('You are not subscribed to any topic. Click here to add subscriptions.')
    return render_template('publish.html', data=data, form=form)


@publish_bp.route('/publish_post', methods=['POST'])
@login_required
def publish_article():
    """
    Publish an article to a topic.

    Returns:
        Response: Redirection to the publisher's home page.
    """
    logger.info("Publish article route accessed.")

    form = PublishForm()
    try:
        form.topic.choices = utils.get_user_data(current_user.id)['topics_subscribed']
        if form.validate_on_submit():
            post = form.post.data
            topic = form.topic.data
            publish_utils.publish_to_azure_service_bus_topic(topic_name=topic, data=post)
            form.post.data = ''
            form.topic.data = ''
            flash("Published successfully.")
        else:
            for error in form.errors:
                flash(f"Error occurred: {error}")
        return redirect(url_for('publish_bp.publisher_home'))
    except Exception as e:
        logger.error("Error occurred while publishing article: %s", e)
        flash("An error occurred.")
        return render_template('publish.html', data=utils.get_user_data(current_user.id), form=form)

publisher/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My App{% endblock %}</title>
    <!-- Include your CSS files here -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
    <!-- Include Bootstrap (if desired) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container-main container-fluid">
        {% block content %}{% endblock %}
    </div>

    <!-- Include Bootstrap JS and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

publisher/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}

<div class="container-fluid container mt-8">
    {% include "navbar.html" %}
    <!-- Section for selecting topics -->
    <div class="mt-4">
        <h2>Select Topics to Subscribe</h2>
        <form method="POST" action="{{ url_for('dashboard_bp.subscribe_topics')}}">
            <div class="form-group">
                <label>Select Topics:</label>
                {% for topic in data.topics.Topics %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="subscribe_topics[]" value="{{ topic }}">
                    <label class="form-check-label">{{ topic }}</label>
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Subscribe</button>
        </form>
    </div>
    <hr>
    <div>
        <br>
        <h4>Subscribed Topics:</h4>
        <form method="POST" action="{{ url_for('dashboard_bp.unsubscribe_topics') }}">
            <ul>
                {% if data.topics_subscribed %}
                    {% for topic in data.topics_subscribed %}
                        <li>
                            <input type="checkbox" name="subscribed_topics[]" value="{{ topic }}" checked>
                            {{ topic }}
                        </li>
                    {% endfor %}
                {% else %}
                    <p>{{ "you are not subscribed to any topic" }}</p>
                {% endif %}
            </ul>
            <button type="submit" class="btn btn-primary">unsubscribe</button>
        </form>
    </div>
    <hr>
    <a href="{{ url_for('publish_bp.publisher_home') }}"> <h4>Navigate to Publishing page</h4> </a>
</div>
{% endblock %}

publisher/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="form-login">

        <div class="container">
           {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="flash-messages">
                  {% for message in messages %}
                    <div class="alert">
                        <h6>{{ message }}</h6>
                    </div>
                  {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
        </div>

        <h2 class="text-center">Login </h2>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="{{ form.email.id }}">{{ form.email.label }}</label>
                {{ form.email(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="{{ form.password.id }}">{{ form.password.label }}</label>
                {{ form.password(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="{{ form.remember_me.id }}">{{ form.remember_me.label }}</label>
                {{ form.remember_me() }}
            </div>
            <div class="d-flex justify-content-center">
                {{ form.submit(class="btn-submit-red") }}
            </div>
            <div class="text-center">
                <a href="{{url_for('register_bp.register_user')}}"> not registered? click here</a>
            </div>
        </form>
    </div>
{% endblock %}

publisher/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Welcome to the Dashboard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ data.username }} <!-- Display logged-in user's name -->
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('login_bp.logout') }}">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

publisher/templates/publish.html
{% extends "base.html" %}

{% block title %}Publish{% endblock %}

{% block content %}
<div class="container-fluid container mt-8">
    {% include "navbar.html" %}
    <h1>Publish a Post</h1>
    <form method="POST" action="{{ url_for('publish_bp.publish_article') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.topic.label(class="form-label") }}
            {{ form.topic(class="form-control form-control-custom") }}
        </div>
        <div class="form-group">
            {{ form.post.label(class="form-label") }}
            {{ form.post(class="form-control form-control-custom", rows="5") }}
        </div>
        <button type="submit" class="btn btn-primary">Publish</button>
    </form>
    <hr>
    <br>
    <div class="container">
           {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="flash-messages">
                  {% for message in messages %}
                    <div class="alert">
                        <h6>{{ message }}</h6>
                    </div>
                  {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
    </div>
</div>
{% endblock %}

publisher/templates/register_user.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
    <div class="form-registration">
        <h2 class="text-center">Register</h2>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="{{ form.name.id }}">{{ form.name.label }}</label>
                {{ form.name(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="{{ form.email.id }}">{{ form.email.label }}</label>
                {{ form.email(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="{{ form.password.id }}">{{ form.password.label }}</label>
                {{ form.password(class="form-control") }}
            </div>
            <div class="form-group">
                <label for="{{ form.confirm_password.id }}">{{ form.confirm_password.label }}</label>
                {{ form.confirm_password(class="form-control") }}
                {% if form.confirm_password.errors and form.is_submitted() %}
                    <div class="error-message">{{ form.confirm_password.errors[0]}}</div>
                {% endif %}
            </div>
            <div class="d-flex justify-content-center">
                {{ form.submit(class="btn-submit-red") }}
            </div>
            <br>
            <div class="text-center">
                <a href="{{ url_for('register_bp.register_user') }}"><h6 class="text-center">Refresh Page</h6></a>
                <a href="{{url_for('login_bp.login')}}">already registered? click here to login</a>
            </div>
        </form>
        <br>
        <div class="container">
           {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="flash-messages">
                  {% for message in messages %}
                    <div class="alert">
                        <h6>{{ message }}</h6>
                    </div>
                  {% endfor %}
                </div>
                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endblock %}